export enum TournamentStatus {
  MYQUIZ = 'MYPLAY',
  PUBLISHED = 'PUBLISHED',
  STARTED = 'STARTED',
  ENDED = 'ENDED',
  MYPLAY = "MYPLAY",
//   CANCELED = 'CANCELED'
}

export enum PortfolioFilter {
  OVERVIEW = 'OVERVIEW',
  STOCKS = 'STOCKS',
  CRYPTOS = 'CRYPTOS',
  FRACTIONAL_BOND = 'FRACTIONAL_BOND'
}

export enum AssetFilter {
  ID_STOCK = 'ID_STOCK',
  US_STOCK = 'US_STOCK',
}

export enum SortingFilter {
  ASCENDING = 'ASCENDING',
  DESCENDING = 'DESCENDING',
  TOP_GAINER_PERCENTAGE = 'TOP_GAINER_PERCENTAGE',
  TOP_GAINER_VALUE = 'TOP_GAINER_VALUE',
  TOP_LOSER_PERCENTAGE = 'TOP_LOSER_PERCENTAGE',
  TOP_LOSER_VALUE = 'TOP_LOSER_VALUE',
}