name: Deploy to DEV - web

on:
  push:
    branches: [update-cicd-dev-ali]

env:
  GITHUB_REGISTRY_IMAGE_NAME: dev-web

permissions:
  id-token: write
  contents: read


jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: aliyun/acr-login@v1
        with:
          login-server: ${{ secrets.ALIBABA_LOGIN_SERVER }}
          username: ${{ secrets.ALIBABA_ACR_USERNAME }}
          password: ${{ secrets.ALIBABA_ACR_PASSWORD }}

      - name: Get version
        run: echo "GITHUB_SHA_SHORT=$(echo ${GITHUB_SHA::7})" >> $GITHUB_ENV

      - name: Build and push docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: |
             crpi-cstuvf7kwe6mse4u.ap-southeast-5.personal.cr.aliyuncs.com/seeds-dev/${{ env.GITHUB_REGISTRY_IMAGE_NAME }}:${{ env.GITHUB_SHA_SHORT }}

      - name: Setup ssh key
        run: |
          mkdir -p $HOME/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY_DEV_ALIBABA }}" > $HOME/.ssh/id_rsa
          chmod 600 $HOME/.ssh/id_rsa

      - name: Download docker image
        run:  |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USERNAME_DEV_ALI }}@${{ secrets.SSH_IP_DEV_ALI }} 'docker login crpi-cstuvf7kwe6mse4u.ap-southeast-5.personal.cr.aliyuncs.com'
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USERNAME_DEV_ALI }}@${{ secrets.SSH_IP_DEV_ALI }} 'docker pull crpi-cstuvf7kwe6mse4u.ap-southeast-5.personal.cr.aliyuncs.com/seeds-dev/${{ env.GITHUB_REGISTRY_IMAGE_NAME }}:${{ env.GITHUB_SHA_SHORT }}'

      - name: Update Docker Compose
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USERNAME_DEV_ALI }}@${{ secrets.SSH_IP_DEV_ALI }} 'versi="$(cat /root/dev-compose/${{ env.GITHUB_REGISTRY_IMAGE_NAME }}/docker-compose.yaml | grep image | cut -d ":" -f 3)" && sed -i "s#image: crpi-cstuvf7kwe6mse4u.ap-southeast-5.personal.cr.aliyuncs.com/seeds-dev/${{ env.GITHUB_REGISTRY_IMAGE_NAME }}:${versi}#image: crpi-cstuvf7kwe6mse4u.ap-southeast-5.personal.cr.aliyuncs.com/seeds-dev/${{ env.GITHUB_REGISTRY_IMAGE_NAME }}:${{ env.GITHUB_SHA_SHORT }}#g" /root/dev-compose/${{ env.GITHUB_REGISTRY_IMAGE_NAME }}/docker-compose.yaml'

      - name: Running container
        run: ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USERNAME_DEV_ALI }}@${{ secrets.SSH_IP_DEV_ALI }} 'docker compose -f /root/dev-compose/${{ env.GITHUB_REGISTRY_IMAGE_NAME }}/docker-compose.yaml up -d'

      - name: Clean up old Docker images on server 
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USERNAME_DEV_ALI }}@${{ secrets.SSH_IP_DEV_ALI }} './cleanup-docker-images.sh '${{ env.GITHUB_REGISTRY_IMAGE_NAME }}' '${{ env.GITHUB_SHA_SHORT }}''

      - name: Clean up ssh key
        run: rm -rf $HOME/.ssh/*