name: Deploy to DEV - Seeds web 1.0

on:
  push:
    branches: [dev]

env:
  GITHUB_REGISTRY: ghcr.io
  GITHUB_REGISTRY_IMAGE_NAME: dev-web
  AWS_ECR: 940544028848.dkr.ecr.ap-southeast-3.amazonaws.com

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
<<<<<<< HEAD
        with:
        # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0

      - id: auth
        name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v0
        with:
          workload_identity_provider: projects/414526331056/locations/global/workloadIdentityPools/pool-github-action/providers/github-action-provider
          service_account: github-action@lithe-window-387706.iam.gserviceaccount.com
          create_credentials_file: true

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.3.0

      - name: Configure docker credential helper artifact registry
        run: gcloud auth configure-docker asia-southeast2-docker.pkg.dev
=======
      #        with:
      # Disabling shallow clone is recommended for improving relevancy of reporting
      #          fetch-depth: 0

      #      - id: auth
      #        name: Authenticate with Google Cloud
      #        uses: google-github-actions/auth@v0
      #        with:
      #          workload_identity_provider: projects/414526331056/locations/global/workloadIdentityPools/pool-github-action/providers/github-action-provider
      #          service_account: github-action@lithe-window-387706.iam.gserviceaccount.com
      #          create_credentials_file: true
      #
      #      - name: Set up Cloud SDK
      #        uses: google-github-actions/setup-gcloud@v0.3.0
      #
      #      - name: Configure docker credential helper artifact registry
      #        run: gcloud auth configure-docker asia-southeast2-docker.pkg.dev
>>>>>>> 7f2931a6c469b2a033bfcdc68bbe1abd86120891

      - name: Get version
        run: echo "GITHUB_SHA_SHORT=$(echo ${GITHUB_SHA::7})" >> $GITHUB_ENV

      - uses: docker/login-action@v2
        with:
          registry: ${{ env.GITHUB_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GH_TOKEN }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_ECR }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_ECR }}
          aws-region: ap-southeast-3

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and push docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags:
            ${{ env.AWS_ECR }}/${{ env.GITHUB_REGISTRY_IMAGE_NAME }}:${{
            env.GITHUB_SHA_SHORT }}
      #            asia-southeast2-docker.pkg.dev/lithe-window-387706/seeds-dev/${{ env.GITHUB_REGISTRY_IMAGE_NAME }}:${{ env.GITHUB_SHA_SHORT }}
      #            ${{ env.GITHUB_REGISTRY }}/seeds-investment/${{ env.GITHUB_REGISTRY_IMAGE_NAME }}:${{ env.GITHUB_SHA_SHORT }}

      - name: Setup ssh key
        run: |
          mkdir -p $HOME/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > $HOME/.ssh/id_rsa
          chmod 600 $HOME/.ssh/id_rsa

      - name: Download docker image
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_IP }} '${{ secrets.AWS_ECR_LOGIN }}'
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_IP }} 'docker pull ${{ env.AWS_ECR }}/${{ env.GITHUB_REGISTRY_IMAGE_NAME }}:${{ env.GITHUB_SHA_SHORT }}'

      - name: Update Docker Compose
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_IP }} 'versi="$(cat /home/ubuntu/app_deploy/dev-web/docker-compose.yaml | grep image | cut -d ":" -f 3)" && sed -i "s#image: ${{ env.AWS_ECR }}/${{ env.GITHUB_REGISTRY_IMAGE_NAME }}:${versi}#image: ${{ env.AWS_ECR }}/${{ env.GITHUB_REGISTRY_IMAGE_NAME }}:${{ env.GITHUB_SHA_SHORT }}#g" /home/ubuntu/app_deploy/dev-web/docker-compose.yaml'

      - name: Running container
        run:
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USERNAME }}@${{
          secrets.SSH_IP }} 'docker-compose -f
          /home/ubuntu/app_deploy/dev-web/docker-compose.yaml up -d'

      - name: Clean up ssh key
        run: rm -rf $HOME/.ssh/*
